export const CSSChallengesData = [
  // Easy Challenges
  {
    title: "Change Text Color",
    description: {
      summary: "Write CSS to change the color of text in a paragraph.",
      topic: "CSS: Basics",
      requirements: [
        "Select a paragraph element and change its text color to blue.",
        "Ensure the text color applies only to the specified paragraph.",
      ],
    },
    tags: ["css basics", "text color"],
    icons: ["faCss3Alt"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Center an Element",
    description: {
      summary: "Use CSS to center an element on the page.",
      topic: "CSS: Layout",
      requirements: [
        "Center a div both horizontally and vertically on the page.",
        "Use Flexbox or other techniques to achieve the centering.",
      ],
    },
    tags: ["css layout", "centering"],
    icons: ["faCss3Alt"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Add Padding to an Element",
    description: {
      summary: "Apply padding to an element to create spacing inside it.",
      topic: "CSS: Spacing",
      requirements: [
        "Add 20px padding to all sides of a div.",
        "Ensure the padding does not affect surrounding elements.",
      ],
    },
    tags: ["css spacing", "padding"],
    icons: ["faCss3Alt"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Apply Border Radius",
    description: {
      summary: "Create rounded corners on an element using CSS.",
      topic: "CSS: Borders",
      requirements: [
        "Add a 10px border radius to a square div to make it appear circular.",
        "Ensure the border radius only applies to the specified element.",
      ],
    },
    tags: ["css borders", "border radius"],
    icons: ["faCss3Alt"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Style Links",
    description: {
      summary:
        "Style links with different colors for hover and visited states.",
      topic: "CSS: Pseudo-classes",
      requirements: [
        "Create a link that changes color on hover and shows a different color when visited.",
        "Use CSS pseudo-classes to style the different states.",
      ],
    },
    tags: ["css pseudo-classes", "links"],
    icons: ["faCss3Alt"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },

  // Medium Challenges
  {
    title: "Create a Card Layout",
    description: {
      summary: "Design a simple card layout using Flexbox.",
      topic: "CSS: Layout",
      requirements: [
        "Use Flexbox to align cards side-by-side.",
        "Add padding and a shadow to each card for visual separation.",
      ],
    },
    tags: ["css layout", "flexbox"],
    icons: ["faCss3Alt"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Responsive Grid",
    description: {
      summary: "Build a responsive grid layout using CSS Grid.",
      topic: "CSS: Grid",
      requirements: [
        "Create a grid layout that displays items in two columns on desktop and one column on mobile.",
        "Use media queries to adjust the grid layout based on screen size.",
      ],
    },
    tags: ["css grid", "responsive design"],
    icons: ["faCss3Alt"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Add a CSS Animation",
    description: {
      summary:
        "Implement a simple animation that changes the color of a button.",
      topic: "CSS: Animations",
      requirements: [
        "Create a button that smoothly changes color over a 2-second animation.",
        "Use CSS keyframes to define the animation steps.",
      ],
    },
    tags: ["css animations", "keyframes"],
    icons: ["faCss3Alt"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Overlay Text on an Image",
    description: {
      summary: "Place text over an image with CSS styling.",
      topic: "CSS: Positioning",
      requirements: [
        "Use CSS positioning to overlay text in the center of an image.",
        "Add styling to make the text readable over the image.",
      ],
    },
    tags: ["css positioning", "overlay"],
    icons: ["faCss3Alt"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Hover Effect",
    description: {
      summary: "Add a hover effect that changes an element's appearance.",
      topic: "CSS: Transitions",
      requirements: [
        "Create a button that changes background color when hovered.",
        "Use a CSS transition for a smooth effect.",
      ],
    },
    tags: ["css transitions", "hover effect"],
    icons: ["faCss3Alt"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },

  // Hard Challenges
  {
    title: "Build a Responsive Navbar",
    description: {
      summary: "Create a responsive navigation bar with dropdown menus.",
      topic: "CSS: Navigation",
      requirements: [
        "Build a navbar with links that stack on mobile and align horizontally on desktop.",
        "Add a dropdown menu that appears on hover.",
      ],
    },
    tags: ["css navigation", "responsive design"],
    icons: ["faCss3Alt"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a CSS Parallax Effect",
    description: {
      summary: "Build a parallax scrolling effect with CSS.",
      topic: "CSS: Effects",
      requirements: [
        "Use CSS background properties to create a parallax effect on scroll.",
        "Apply the effect to a large background image in a webpage section.",
      ],
    },
    tags: ["css effects", "parallax"],
    icons: ["faCss3Alt"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Design a CSS Tooltip",
    description: {
      summary: "Create a tooltip that appears when hovering over text.",
      topic: "CSS: Tooltips",
      requirements: [
        "Build a tooltip using CSS that appears above text on hover.",
        "Style the tooltip with a background and pointer arrow.",
      ],
    },
    tags: ["css tooltips", "hover effect"],
    icons: ["faCss3Alt"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a CSS Dropdown Menu",
    description: {
      summary: "Build a dropdown menu using CSS only.",
      topic: "CSS: Dropdowns",
      requirements: [
        "Create a dropdown menu that appears on hover.",
        "Use CSS positioning to display the dropdown items correctly.",
      ],
    },
    tags: ["css dropdown", "hover effect"],
    icons: ["faCss3Alt"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Build a CSS Accordion",
    description: {
      summary: "Create an accordion with CSS to show and hide content.",
      topic: "CSS: Layout",
      requirements: [
        "Use CSS to toggle visibility of content in accordion sections.",
        "Style each section with spacing and borders.",
      ],
    },
    tags: ["css layout", "accordion"],
    icons: ["faCss3Alt"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
];
