export const HTMLChallengesData = [
  // Easy Challenges
  {
    title: "Basic HTML Structure",
    description: {
      summary:
        "Create a basic HTML structure with header, main, and footer sections.",
      topic: "HTML: Basics",
      requirements: [
        "Create an HTML document with a header, main content, and footer.",
        "Add a title to the document.",
      ],
    },
    tags: ["html structure", "basics"],
    icons: ["faHtml5"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Simple Form",
    description: {
      summary:
        "Design a simple form with text inputs, radio buttons, and a submit button.",
      topic: "HTML: Forms",
      requirements: [
        "Include fields for name, email, and gender (radio buttons).",
        "Add a submit button to the form.",
      ],
    },
    tags: ["html form", "input elements"],
    icons: ["faHtml5"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Embed an Image",
    description: {
      summary: "Add an image to your HTML document with alt text.",
      topic: "HTML: Images",
      requirements: [
        "Include an image with a source attribute and alt text for accessibility.",
      ],
    },
    tags: ["html images", "accessibility"],
    icons: ["faHtml5"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Hyperlink",
    description: {
      summary: "Add a clickable hyperlink to another webpage.",
      topic: "HTML: Links",
      requirements: [
        "Create an anchor tag that links to an external website.",
        "Use meaningful text for the link.",
      ],
    },
    tags: ["html links", "anchor tag"],
    icons: ["faHtml5"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Simple List",
    description: {
      summary: "Build an ordered and unordered list in HTML.",
      topic: "HTML: Lists",
      requirements: [
        "Create an unordered list with three items.",
        "Create an ordered list with three items.",
      ],
    },
    tags: ["html lists"],
    icons: ["faHtml5"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },

  // Medium Challenges
  {
    title: "Add a Table",
    description: {
      summary: "Create a basic table with rows and columns.",
      topic: "HTML: Tables",
      requirements: [
        "Create a table with three rows and three columns.",
        "Add header cells in the first row.",
      ],
    },
    tags: ["html tables"],
    icons: ["faHtml5"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Form with Validation",
    description: {
      summary: "Build a form with required fields and email validation.",
      topic: "HTML: Forms",
      requirements: [
        "Include fields for name, email, and password.",
        "Add HTML validation to ensure email format and required fields.",
      ],
    },
    tags: ["html form", "validation"],
    icons: ["faHtml5"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Contact Us Page",
    description: {
      summary: "Build a Contact Us page with a form and address section.",
      topic: "HTML: Layout",
      requirements: [
        "Add a form with name, email, and message fields.",
        "Include a section with address and contact details.",
      ],
    },
    tags: ["html layout", "form"],
    icons: ["faHtml5"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Add Semantic HTML Tags",
    description: {
      summary: "Implement semantic tags in a webpage layout.",
      topic: "HTML: Semantics",
      requirements: [
        "Use tags like <header>, <footer>, <article>, and <section> to create a page layout.",
      ],
    },
    tags: ["html semantics"],
    icons: ["faHtml5"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Navbar with Links",
    description: {
      summary: "Design a simple navigation bar with clickable links.",
      topic: "HTML: Navigation",
      requirements: [
        "Add a navbar with links to Home, About, and Contact pages.",
        "Use unordered list and anchor tags for navigation.",
      ],
    },
    tags: ["html navigation", "navbar"],
    icons: ["faHtml5"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },

  // Hard Challenges
  {
    title: "Create a Login Page with HTML and CSS",
    description: {
      summary: "Build a complete login page layout with forms and styling.",
      topic: "HTML & CSS: Layout",
      requirements: [
        "Create a login form with username and password fields.",
        "Use CSS to style the page with a centered form.",
      ],
    },
    tags: ["html form", "css layout"],
    icons: ["faHtml5"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Responsive Grid Layout",
    description: {
      summary: "Build a responsive grid layout for a gallery or product list.",
      topic: "HTML & CSS: Grid",
      requirements: [
        "Use CSS Grid to create a responsive layout with multiple items.",
        "Ensure the layout adjusts based on screen size.",
      ],
    },
    tags: ["html grid", "responsive design"],
    icons: ["faHtml5"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Implement an Image Slider",
    description: {
      summary: "Create a basic image slider with HTML and JavaScript.",
      topic: "HTML, CSS, JavaScript: Images",
      requirements: [
        "Implement an image slider with 'Next' and 'Previous' buttons.",
        "Use JavaScript to change images on button clicks.",
      ],
    },
    tags: ["html images", "javascript"],
    icons: ["faHtml5"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Build a Multi-Step Form",
    description: {
      summary: "Create a form with multiple steps and a progress indicator.",
      topic: "HTML: Forms",
      requirements: [
        "Divide the form into multiple sections.",
        "Use JavaScript to move between steps and indicate progress.",
      ],
    },
    tags: ["html form", "javascript"],
    icons: ["faHtml5"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create an Accessible Webpage",
    description: {
      summary: "Design a webpage with accessibility best practices.",
      topic: "HTML: Accessibility",
      requirements: [
        "Use appropriate ARIA roles and alt text.",
        "Ensure good color contrast and keyboard navigation.",
      ],
    },
    tags: ["html accessibility"],
    icons: ["faHtml5"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Create a Blog Post Layout",
    description: {
      summary: "Build a layout for a blog post page with comments section.",
      topic: "HTML & CSS: Layout",
      requirements: [
        "Create a layout with title, content, and comments sections.",
        "Use CSS to style the page with readable typography.",
      ],
    },
    tags: ["html layout", "blog post"],
    icons: ["faHtml5"],
    difficulty: "Hard",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
];
