export const JavaScriptChallengesData = [
  {
    title: "Change Background Color",
    description: {
      summary:
        "Write a function that changes the background color of a webpage.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Implement a button that, when clicked, changes the background color of the webpage.",
        "Use different colors for each click, cycling through an array of colors.",
      ],
    },
    tags: ["dom manipulation", "css"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink:
      "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXF5eHNrYjZ4ZDB4YXc1cG0wejl6NmNjemp4aG9wZzd0bWxxNmp1cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8J8ismUjoOP7IY4PFs/giphy.gif",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Display Current Date and Time",
    description: {
      summary: "Create a function that displays the current date and time.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Implement a button that displays the current date and time on the webpage when clicked.",
        "The date and time should update each time the button is clicked.",
      ],
    },
    tags: ["dom manipulation", "date"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink:
      "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGd3d2ZpNHJ0MDM1czJ3a3RqOGtpaGEwbzdkdW05bDRydmdpN29tNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/zUUIeVAZgp0ImcDAXS/giphy.gif",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Counter Button",
    description: {
      summary:
        "Write a function that increments a counter displayed on the webpage.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Create a button that, when clicked, increments a counter displayed on the page.",
        "The counter should start from 0 and increase by 1 with each click.",
      ],
    },
    tags: ["dom manipulation", "counter"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink: "https://s4.ezgif.com/tmp/ezgif-4-a0cc2b199e.gif",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Toggle Visibility of Text",
    description: {
      summary: "Write a function to toggle the visibility of a paragraph.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Create a button that, when clicked, toggles the visibility of a paragraph on the page.",
        "The button text should change to 'Hide' or 'Show' based on the paragraph's visibility.",
      ],
    },
    tags: ["dom manipulation", "toggle"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Add Item to List",
    description: {
      summary: "Create a function to add a new item to an unordered list.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Create an input field and button that adds the text from the input field as a new list item.",
        "The new item should appear at the end of an unordered list each time the button is clicked.",
      ],
    },
    tags: ["dom manipulation", "list"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Remove List Item",
    description: {
      summary: "Write a function to remove the last item in an unordered list.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Add a button that removes the last item in an unordered list each time it is clicked.",
        "If there are no items left in the list, disable the button.",
      ],
    },
    tags: ["dom manipulation", "list"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Image Slider",
    description: {
      summary: "Create a simple image slider with Next and Previous buttons.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Implement two buttons, 'Next' and 'Previous,' that allow users to navigate through a series of images.",
        "The images should cycle back to the start after the last image.",
      ],
    },
    tags: ["dom manipulation", "images"],
    icons: ["faJsSquare"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Change Text on Hover",
    description: {
      summary: "Write a function that changes the text of an element on hover.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Create a paragraph element that changes its text when the mouse hovers over it.",
        "The text should revert back to the original when the mouse leaves the element.",
      ],
    },
    tags: ["dom manipulation", "hover"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Form Validation",
    description: {
      summary: "Create a function to validate a simple form input.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Implement a form with an input field that requires a non-empty value.",
        "Display a warning message if the user tries to submit the form with an empty field.",
      ],
    },
    tags: ["dom manipulation", "forms"],
    icons: ["faJsSquare"],
    difficulty: "Medium",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
  {
    title: "Character Counter",
    description: {
      summary: "Write a function that counts the characters in a text area.",
      topic: "JavaScript: DOM Manipulation",
      requirements: [
        "Create a text area and display the character count below it.",
        "Update the character count each time the user types in the text area.",
      ],
    },
    tags: ["dom manipulation", "text"],
    icons: ["faJsSquare"],
    difficulty: "Easy",
    demoLink: "",
    author: "Anup K Jana",
    authorProfession: "Frontend Developer",
    authorLinkedin: "https://linkedin.com/in/anupkumarjana",
  },
];
